apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: data-science-subscription
  namespace: redhat-ods-operator
spec:
  channel: "$channel"
  startingCSV: "$currentCSV"
  name: "$name"
  source: "$catalog_source"
  sourceNamespace: "$catalog_source_namespace"
  installPlanApproval: Automatic