apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: $channel
  startingCSV: "$currentCSV"
  name: "$name"
  source: "$catalog_source"
  sourceNamespace: $catalog_source_namespace
  installPlanApproval: Automatic